name: todotree
description: "ToDo notes in an unlimited tree structure"
publish_to: 'none'

version: '2.2.2+14'

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  window_manager: ^0.3.8
  collection: ^1.18.0
  path_provider: ^2.1.3
  yaml_writer: ^2.0.0
  yaml: ^3.1.2
  move_to_background: ^1.0.2
  intl: ^0.19.0
  file_picker: ^8.0.3
  settings_ui: ^2.0.2
  shared_preferences: ^2.2.3
  flutter_slidable: ^3.1.0
  http: ^1.2.1
  confetti: ^0.7.0
  swipe_to: ^1.0.6
  shared_storage: ^0.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true
  fonts:
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf

flutter_launcher_icons:
  image_path: "assets/icon.jpeg" 
  android: true
  adaptive_icon_background: "#f7f6f1"
  adaptive_icon_foreground: "assets/icon.jpeg"
