name: todotree
description: "flutter project"
publish_to: 'none'

version: 1.0.0+10

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.0
  window_manager: ^0.3.8
  collection: ^1.18.0
  path_provider: ^2.1.2
  yaml_writer: ^2.0.0
  yaml: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
